# Generated by Django 4.2.7 on 2023-12-02 07:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("answers", "0002_remove_answer_question_answeritem_question"),
    ]

    operations = [
        migrations.RenameField(
            model_name="answeritem",
            old_name="quetion_response_option",
            new_name="question_response_option",
        ),
    ]
