# Generated by Django 4.2.7 on 2023-12-02 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0002_alter_patient_addiction_level_and_more"),
        (
            "answers",
            "0003_rename_quetion_response_option_answeritem_question_response_option",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="answer",
            name="user",
        ),
        migrations.AddField(
            model_name="answer",
            name="patient",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="patients.patient",
            ),
            preserve_default=False,
        ),
    ]
