# Generated by Django 4.2.7 on 2023-12-02 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("answers", "0004_remove_answer_user_answer_patient"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answeritem",
            name="answer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="answers",
                to="answers.answer",
            ),
        ),
    ]
