# Generated by Django 4.2.7 on 2024-01-06 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0005_alter_answeritem_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
