# Generated by Django 4.2.7 on 2023-11-05 00:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="addiction_level",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(
                        0, message="Value must be greater than or equal to 0."
                    ),
                    django.core.validators.MaxValueValidator(
                        100, message="Value must be less than or equal to 100"
                    ),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="anxiety_score",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(
                        0, message="Value must be greater than or equal to 0."
                    ),
                    django.core.validators.MaxValueValidator(
                        100, message="Value must be less than or equal to 100"
                    ),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="average_hours_of_play_per_week",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(
                        0, message="Value must be greater than or equal to 0."
                    ),
                    django.core.validators.MaxValueValidator(
                        168, message="Value must be less than or equal to 168"
                    ),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="average_month_of_play",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(
                        0, message="Value must be greater than or equal to 0."
                    ),
                    django.core.validators.MaxValueValidator(
                        100, message="Value must be less than or equal to 100"
                    ),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="depression_score",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(
                        0, message="Value must be greater than or equal to 0."
                    ),
                    django.core.validators.MaxValueValidator(
                        100, message="Value must be less than or equal to 100"
                    ),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="excessive_sleepiness_score",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(
                        0, message="Value must be greater than or equal to 0."
                    ),
                    django.core.validators.MaxValueValidator(
                        100, message="Value must be less than or equal to 100"
                    ),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="insomnia_score",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(
                        0, message="Value must be greater than or equal to 0."
                    ),
                    django.core.validators.MaxValueValidator(
                        100, message="Value must be less than or equal to 100"
                    ),
                ],
            ),
        ),
    ]
