# Generated by Django 4.2.7 on 2023-11-04 10:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="phone",
            field=models.CharField(default="", max_length=12),
            preserve_default=False,
        ),
    ]
