# Generated by Django 4.2.6 on 2023-11-03 18:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_customuser_is_staff"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="gender",
            field=models.CharField(
                choices=[("M", "male"), ("F", "female")], default="M", max_length=1
            ),
        ),
    ]
