# Generated by Django 4.2.7 on 2023-11-27 11:10

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_alter_customuser_user_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=accounts.models.user_image_namer
            ),
        ),
    ]
