# Generated by Django 4.2.7 on 2023-11-30 22:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_alter_customuser_gender_alter_customuser_user_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customuser",
            old_name="created",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="customuser",
            old_name="updated",
            new_name="updated_at",
        ),
    ]
