# Generated by Django 4.2.7 on 2023-12-01 11:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0008_alter_customuser_gender_alter_customuser_user_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="gender",
            field=models.CharField(
                choices=[(1, "male"), (2, "female")], default=1, max_length=1
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="user_type",
            field=models.CharField(
                choices=[(1, "paitent"), (2, "doctor"), (3, "admin")],
                default=1,
                max_length=10,
            ),
        ),
    ]
