# Generated by Django 4.2.7 on 2023-12-01 18:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0009_alter_customuser_gender_alter_customuser_user_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="gender",
            field=models.CharField(
                choices=[("MALE", "male"), ("FEMALE", "female")],
                default="MALE",
                max_length=6,
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("PAITENT", "paitent"),
                    ("DOCTOR", "doctor"),
                    ("ADMIN", "admin"),
                ],
                default="PAITENT",
                max_length=10,
            ),
        ),
    ]
