# Generated by Django 4.2.7 on 2023-12-02 22:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0010_alter_customuser_gender_alter_customuser_user_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("PATIENT", "patient"),
                    ("DOCTOR", "doctor"),
                    ("ADMIN", "admin"),
                ],
                default="PATIENT",
                max_length=10,
            ),
        ),
    ]
