# Generated by Django 4.2.7 on 2023-12-01 18:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UiSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "theme",
                    models.BooleanField(
                        choices=[("DARK", "dark"), ("LIGHT", "light")],
                        default="LIGHT",
                        max_length=5,
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[("EN", "en"), ("AR", "ar")], default="EN", max_length=2
                    ),
                ),
                (
                    "qt_display_type",
                    models.CharField(
                        choices=[("GRID", "grid"), ("LIST", "list")],
                        default="LIST",
                        max_length=4,
                    ),
                ),
                ("qt_show_alph", models.BooleanField(default=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
