# Generated by Django 4.2.7 on 2023-12-02 09:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("uisettings", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uisettings",
            name="language",
            field=models.CharField(
                choices=[("en", "English"), ("ar", "Arabic")],
                default="en",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="uisettings",
            name="qt_display_type",
            field=models.CharField(
                choices=[("grid", "Grid"), ("list", "List")],
                default="list",
                max_length=4,
            ),
        ),
        migrations.AlterField(
            model_name="uisettings",
            name="theme",
            field=models.CharField(
                choices=[("dark", "Dark"), ("light", "Light")],
                default="light",
                max_length=5,
            ),
        ),
    ]
