version: "3.8"
services:
  backend:
    container_name: mztool_backend
    build:
      context: ./backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - "./backend/static:/backend/static"
      - "./backend/media:/backend/media"
    restart: unless-stopped
    depends_on:
      - db
  web:
    container_name: mztool_web
    build:
      context: ./frontend
    # volumes:
    #   - "./frontend/dist:/web/dist"
    # ports:
      # - "3000:3000"
  db:
    container_name: mztool_mysql
    image: mysql:8.0
    #ports:
      #"3306:3306"
    env_file:
      - .env
    volumes:
      - "./volumes/db:/var/lib/mysql"
    restart: unless-stopped
  nginx:
    image: nginx:latest
    container_name: mztool_nginx
    ports:
      - "9000:80"
    volumes:
      - "./nginx:/etc/nginx"
      - "./frontend/dist:/var/www/web/dist"
      - "./backend/static:/var/www/backend/static"
      - "./backend/media:/var/www/backend/media"
