# Generated by Django 4.2.7 on 2023-11-24 00:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="send_date",
            field=models.DateField(default=datetime.date(2023, 11, 24)),
        ),
    ]
