# Generated by Django 4.2.7 on 2023-11-27 23:32

import contacts.validator
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0004_alter_contact_send_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="phone_number",
            field=models.CharField(
                max_length=15, validators=[contacts.validator.validate_phone_number]
            ),
        ),
    ]
