# Generated by Django 4.2.6 on 2023-11-03 20:08

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Paitent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "addiction_level",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(
                                0, message="value must be greater than or equal to 0 "
                            ),
                            django.core.validators.MaxValueValidator(
                                100, message="value must be less than or equal to 100"
                            ),
                        ]
                    ),
                ),
                (
                    "average_hours_of_play_per_week",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(
                                0, message="Value must be greater than or equal to 0."
                            )
                        ]
                    ),
                ),
                (
                    "average_month_of_play",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(
                                0, message="Value must be greater than or equal to 0."
                            )
                        ]
                    ),
                ),
                (
                    "insomnia_score",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(
                                0, message="Value must be greater than or equal to 0."
                            )
                        ]
                    ),
                ),
                (
                    "excessive_sleepiness_score",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(
                                0, message="Value must be greater than or equal to 0."
                            )
                        ]
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
