# Generated by Django 4.2.6 on 2023-11-03 20:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("paitents", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="paitent",
            name="anxiety_score",
            field=models.PositiveIntegerField(
                default=1,
                validators=[
                    django.core.validators.MinValueValidator(
                        0, message="Value must be greater than or equal to 0."
                    )
                ],
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="paitent",
            name="depression_score",
            field=models.PositiveIntegerField(
                default=1,
                validators=[
                    django.core.validators.MinValueValidator(
                        0, message="Value must be greater than or equal to 0."
                    )
                ],
            ),
            preserve_default=False,
        ),
    ]
