# Generated by Django 4.2.7 on 2023-11-28 00:05

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Reviews",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(max_length=200)),
                (
                    "rating",
                    models.IntegerField(
                        default=3,
                        validators=[
                            django.core.validators.MinLengthValidator(
                                1, message=" value must be greater than or equals to 1 "
                            ),
                            django.core.validators.MaxLengthValidator(
                                5, message="value must be less then or equals to 5 "
                            ),
                        ],
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "writer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
