# Generated by Django 4.2.7 on 2023-11-28 11:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reviews", "0002_alter_reviews_text"),
    ]

    operations = [
        migrations.RenameField(
            model_name="reviews",
            old_name="writer",
            new_name="user",
        ),
        migrations.AlterField(
            model_name="reviews",
            name="rating",
            field=models.IntegerField(default=3),
        ),
    ]
